### ISSUE TITLE
Unable to connect to the login queue of Fortnite, try again later

### ISSUE THREAD

**Issue by Repressoh** [Lawin0129/LawinServerV2#1]
Hi! I configured the discord bot and the mongodb, created an account with the bot and tried to login in fortnite. But when i try to login with mail and password or mail and exchangecode, says that the authentication failed, unable to access in fortnite servers. 

![image](https://user-images.githubusercontent.com/85702320/195973825-15a8e129-1966-45a1-ad91-a1d76e89a18a.png)

I tried on build 7.30 and 10.40.

[This is the script i use for fiddler](https://pastebin.com/PqeKuQAK)

Thanks for any help

## SOLUTION : https://github.com/Lawin0129/LawinServerV2/issues/1#issuecomment-1295817521

**Comment by PRO100KatYT** [comment]
Replace "http://serverpubip:80" with "http://127.0.0.1:8080" in your script.

**Comment by Repressoh** [comment]
> Replace "http://serverpubip:80" with "http://127.0.0.1:8080" in your script.

i wrote serverpubip just to censor it, but i use the public ip of the machine where i host the lawinserver

**Comment by Repressoh** [comment]
I searched for something and by starting the launcher with `FortniteLauncher -NOSSLPINNING -skippatchcheck -epicportal -HTTP=WinINet` i can pass the login screen, but it's stuck on "Unable to access to login queue"

![image](https://user-images.githubusercontent.com/85702320/195974894-849e0dda-de9d-4535-8014-478b54940026.png)

**Comment by PRO100KatYT** [comment]
Try using this launcher for Season 7 if you haven't already https://drive.google.com/file/d/1xXkIY4YfF1_pSRYdy5BtFC4yQCOzutmU/view?usp=sharing
(copy and paste both files from the zip to the Win64 folder)

**Comment by Repressoh** [comment]
> Try using this launcher for Season 7 if you haven't already https://drive.google.com/file/d/1xXkIY4YfF1_pSRYdy5BtFC4yQCOzutmU/view?usp=sharing (copy and paste both files from the zip to the Win64 folder)

Doesn't work, same error

![image](https://user-images.githubusercontent.com/85702320/195979080-92833cf0-1363-41dc-be56-5eb5a54ed205.png)

**Comment by Repressoh** [comment]
Ok so, this looks like it's my build problem

**Comment by Repressoh** [comment]
I redownloaded the build and i still have the problem, so i think its not a build problem

**Comment by Lawin0129** [comment]
Season 6 - 9 (only works up to client 9.10): https://drive.google.com/file/d/1xXkIY4YfF1_pSRYdy5BtFC4yQCOzutmU/view?usp=sharing

**Comment by Lawin0129** [comment]
Launcher ^

**Comment by Lawin0129** [comment]
Put both of the files in your Binaries/Win64, replace all and run "Launcher.bat"

**Comment by Repressoh** [comment]
> Season 6 - 9 (only works up to client 9.10): https://drive.google.com/file/d/1xXkIY4YfF1_pSRYdy5BtFC4yQCOzutmU/view?usp=sharing

i'm arleady using this, @PRO100KatYT linked it to me yesterday

**Comment by Lawin0129** [comment]
> Put both of the files in your Binaries/Win64, replace all and run "Launcher.bat"

Are you doing this?

**Comment by Repressoh** [comment]
> > Put both of the files in your Binaries/Win64, replace all and run "Launcher.bat"
> 
> Are you doing this?

yes

**Comment by AntogamerYT** [comment]
If someone needs this, use [neonite launcher](https://github.com/NeoniteDev/NeoniteV2/raw/aac5e039a98dea00b4d0bf46ddc4a17d05e44076/public/launcher.zip) for 9.30? and higher (XMPP and CloudStorage wont work, and you will have to redirect localhost:5595 using a fiddlerscript like [this one](https://pastebin.com/GZnE0nWn))

**Comment by AntogamerYT** [comment]
@Lawin0129 ^ you should put this on the readme imo, same with the other launcher

**Comment by Lawin0129** [comment]
![image](https://user-images.githubusercontent.com/56766256/196043512-19a5a01d-3d41-4614-9da1-3eee63f61fa8.png)
Remove that / from the fiddlerscript

**Comment by AntogamerYT** [comment]
oops, done: https://pastebin.com/r9FKNPHw

**Comment by Lawin0129** [comment]
![image](https://user-images.githubusercontent.com/56766256/196043637-2336131e-5698-409a-9b3c-c25ad02e1ece.png)
Also remember, that won't work

**Comment by AntogamerYT** [comment]
oh fuck right, i took the old script i used (the one before you fixed it for me), [this should work](https://pastebin.com/L0eqXGaY), both for neonite and launch.bat

**Comment by Repressoh** [comment]
i think that the problem is libcurl, as in the logs i can see `LogHttp: Warning: 00007FE4FCC21640: request failed, libcurl error: 35 (SSL connect error)`

**Comment by Repressoh** [comment]
Today i reinstalled Windows and i redownloaded build 7.30 and started by using the custom fortnitelauncher and launcher.bat provided by @Lawin0129 but I still have the same problem with libcurl

**Comment by Repressoh** [comment]
I THINK I FOUND A SOLUTION

Just download rebootlauncher from microsoft store or from [github releases](https://github.com/Auties00/reboot_launcher/releases)

Then open fiddler, put in fiddlerscript your script and leave it open, **DO NOT START LAWINSERVER FROM REBOOT LAUNCHER** , add the game with memory fix inject and start it!
