### ISSUE TITLE
cant go in lobby

### ISSUE THREAD

**Issue by timeapis** [Lawin0129/LawinServerV2#102]
when i press on play battleroyal i have this screen @Lawin0129 (sorry for ping)
![image](https://github.com/Lawin0129/LawinServerV2/assets/153199278/18f60177-5c12-4e81-ace2-d03f785254fd)

**Comment by noxxUY** [comment]
probably using the same account for gameserver and playing

**Comment by timeapis** [comment]
> probably using the same account for gameserver and playing

but i never had this issue before even tho same acc for gs

**Comment by noxxUY** [comment]
idk, try using another account and check if that fixes it

**Comment by timeapis** [comment]
> idk, try using another account and check if that fixes it

ok i will try now

**Comment by timeapis** [comment]
@noxxUY thank you very much it worked

**Comment by noxxUY** [comment]
np <3
