### ISSUE TITLE
Need help removeing all skinds and stuff from the default folder

### ISSUE THREAD

**Issue by CodingRule** [Lawin0129/LawinServerV2#103]
Hey! So I'm trying to create a private server where players have to reach level 100 to unlock all the skins how would that be done?

**Comment by xLoigi** [comment]
You would need to empty the default profile items or you could use my files that i already modified.
[DefaultProfiles.zip](https://github.com/Lawin0129/LawinServerV2/files/13762890/DefaultProfiles.zip)

**Comment by CodingRule** [comment]
thx
