### ISSUE TITLE
SEASON 4 LOGIN BROKEN 4.1 4.2 4.4 and 4.5

### ISSUE THREAD

**Issue by godbot100** [Lawin0129/LawinServerV2#111]
Please I need help finding a fix to this, I know it’s an issue with Lawin server v2, so what could be made to fix this issue, I know other backends in the past have worked fine with s4 builds so does this one have login issues.

**Comment by Lawin0129** [comment]
show me the error message

**Comment by godbot100** [comment]
@Lawin0129 
![image](https://github.com/Lawin0129/LawinServerV2/assets/72945750/87054d13-8ee0-4a8c-b8f4-77b29a4ad370

**Comment by godbot100** [comment]
LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-FB663B4848BD166B7D6FDCAECE3C4BDB-B73EF91945B3FABE35DF71850B583976 code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=Token is missing key ID value errorraw={"errorCode":"errors.com.epicgames.common.oauth.invalid_token","errorMessage":"Token is missing key ID value","messageVars":[],"numericErrorCode":1014,"originatingService":"lightswitch","intent":"prod"}
LogOnline: Warning: OSS: QueryServiceStatus request failed. Token is missing key ID value
LogOnlineAccount: Warning: [UOnlineAccountCommon::OnQueryServiceStatusComplete] Unknown service status return from service availability - lightswitch service down or other unexpected error.  Allowing play to continue if client previously saw UP response.
LogOnlineAccount: Warning: [UOnlineAccountCommon::AbortLoggingIn] Aborting OnlineAccountCommon login due to error [CurrentLoginStep=CheckServiceAvailability] [LoginResult=26] [DisplayError=Network failure when attempting to check service status.] [DetailedError=Service status request failed for service Fortnite with error: Token is missing key ID value]

**Comment by godbot100** [comment]
```LogOnlineAccount: Display: [UOnlineAccountCommon::ContinueLoggingIn] Login: Checking Epic services queue... (LoginWaitingRoom)
LogOnlineAccount: Display: [UOnlineAccountCommon::ContinueLoggingIn] Login: Signing in to Epic services... (LoggingIn)
LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-7AA3B96A4D85FD05045EB5B3B3B21E6C-DCFB45D84AF939998B1E19A6A49004F5 code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=The JWT token you are using has a blank or missing kid claim errorraw={"errorCode":"errors.com.epicgames.common.oauth.invalid_token","errorMessage":"The JWT token you are using has a blank or missing kid claim","messageVars":[],"numericErrorCode":1014,"originatingService":"com.epicgames.account.public","intent":"prod"}
LogOnline: Warning: OSS: QueryExternalAuths request failed. The JWT token you are using has a blank or missing kid claim
LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-7AA3B96A4D85FD05045EB5B3B3B21E6C-2B8A588C479733EAC5363987B598149F code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=The JWT token you are using has a blank or missing kid claim errorraw={"errorCode":"errors.com.epicgames.common.oauth.invalid_token","errorMessage":"The JWT token you are using has a blank or missing kid claim","messageVars":[],"numericErrorCode":1014,"originatingService":"com.epicgames.account.public","intent":"prod"}
LogOnline: Warning: OSS: QueryLoggedInUserInfo request failed. The JWT token you are using has a blank or missing kid claim
LogOnlineAccount: Warning: [UOnlineAccountCommon::AbortLoggingIn] Aborting OnlineAccountCommon login due to error [CurrentLoginStep=LoggingIn] [LoginResult=13] [DisplayError=Unable to login to Fortnite servers. Please try again later.] [DetailedError=Failed to login new user. Error=[The JWT token you are using has a blank or missing kid claim]]
LogOnlineAccount: Warning: [UOnlineAccountCommon::ForceLogout] ForceLogout (local=true) requested with reason "Unable to login to Fortnite servers. Please try again later."
LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-7AA3B96A4D85FD05045EB5B3B3B21E6C-6687795345451E8036B073A729D03443 code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=The JWT token you are using has a blank or missing kid claim errorraw={"errorCode":"errors.com.epicgames.common.oauth.invalid_token","errorMessage":"The JWT token you are using has a blank or missing kid claim","messageVars":[],"numericErrorCode":1014,"originatingService":"com.epicgames.account.public","intent":"prod"}
LogOnline: Warning: OSS: Kill auth sessions request failed. The JWT token you are using has a blank or missing kid claim```

**Comment by UWUFN** [comment]
can confirm i also get these errors, on these specific versions

**Comment by godbot100** [comment]
```LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-FB663B4848BD166B7D6FDCAECE3C4BDB-B73EF91945B3FABE35DF71850B583976 code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=Token is missing key ID value errorraw={"errorCode":"errors.com.epicgames.common.oauth.invalid_token","errorMessage":"Token is missing key ID value","messageVars":[],"numericErrorCode":1014,"originatingService":"lightswitch","intent":"prod"}
LogOnline: Warning: OSS: QueryServiceStatus request failed. Token is missing key ID value
LogOnlineAccount: Warning: [UOnlineAccountCommon::OnQueryServiceStatusComplete] Unknown service status return from service availability - lightswitch service down or other unexpected error.  Allowing play to continue if client previously saw UP response.
LogOnlineAccount: Warning: [UOnlineAccountCommon::AbortLoggingIn] Aborting OnlineAccountCommon login due to error [CurrentLoginStep=CheckServiceAvailability] [LoginResult=26] [DisplayError=Network failure when attempting to check service status.] [DetailedError=Service status request failed for service Fortnite with error: Token is missing key ID value]```

**Comment by godbot100** [comment]
There are 3 different errors

**Comment by UWUFN** [comment]
just want to go more in depth, the errors that will pop up on screen rather than on logs:

1. at the login screen, having to make you login manually, which will either work or not work (error: The JWT token you are using has a blank or missing kid claim)
2. cannot connect to fortnite servers
3. network failure when attempting to check service status

**Comment by godbot100** [comment]
Logging in manually has never worked for me

**Comment by Lawin0129** [comment]
I just fixed it in the latest commit, it has nothing to do with the backend, it just fails to redirect the network restrictions endpoint so disabling it with a hotfix will work.

**Comment by Lawin0129** [comment]
Nevermind, I just saw that your logs have more issues than that, that's to do with the ssl bypass dll, not the backend.

**Comment by UWUFN** [comment]
i've tried with both Aurora.Runtime & Cobalt, both seem to not work. it's only an issue on V2 & not V1.

**Comment by Lawin0129** [comment]
```
{
  "errorCode" : "errors.com.epicgames.common.oauth.invalid_token",
  "errorMessage" : "Token is missing key ID value",
  "messageVars" : [ ],
  "numericErrorCode" : 1014,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}
```

This is an error returned by the epic services, Lawin V2 has no such error response anywhere.

**Comment by UWUFN** [comment]
would it be weird for it to actually log you in if you have fortnite focused?

**Comment by Lawin0129** [comment]
Season 4 is just weird, i dont know

**Comment by UWUFN** [comment]
thanks for the quick replies

**Comment by godbot100** [comment]
lol, the question is why does it work fine on v1 is it cause it doesn’t use accounts like v2, I’m less knowledgeable on this.

**Comment by Lawin0129** [comment]
maybe some differences in hotfixes and responses cause the client to behave differently if thats the case

**Comment by godbot100** [comment]
Interesting

**Comment by Lawin0129** [comment]
Or its probably just a coincidence, those requests sometimes get redirected and sometimes not

**Comment by UWUFN** [comment]
![image](https://github.com/Lawin0129/LawinServerV2/assets/106402404/88685638-6503-44d0-9166-7fef7a28cd81)

LMAOOO

**Comment by godbot100** [comment]
WTF

**Comment by Lawin0129** [comment]
is that with the new commit?

**Comment by UWUFN** [comment]
yes, only thing i tried was not being focused into fortnite

**Comment by Lawin0129** [comment]
I transferred those hotfixes directly from Lawin V1

**Comment by UWUFN** [comment]
i'll try again, this is so odd

**Comment by godbot100** [comment]
I mean era got 4.5 working on their backend a while ago so it’s definitely possible

**Comment by UWUFN** [comment]
![image](https://github.com/Lawin0129/LawinServerV2/assets/106402404/c848a56b-e507-4f2f-b7b1-f0bb9ba1f478)

```
LogOnline: Warning: OSS: Invalid response. CorrId=UE4-81c8e72541d79dc106c902b8c5330764-20E777284EA8FA4ADD21CBADFBF5C5B0-44FFE1204D86F4E97000ED9BBA8566D1 code=401 errorcode=errors.com.epicgames.common.oauth.invalid_token errormessage=Token is missing key ID value errorraw={
  "errorCode" : "errors.com.epicgames.common.oauth.invalid_token",
  "errorMessage" : "Token is missing key ID value",
  "messageVars" : [ ],
  "numericErrorCode" : 1014,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}
LogOnline: Warning: MCP: EnumerateFiles request failed. Token is missing key ID value
LogHotfixManager: Error: Enumeration of hotfix files failed
```

**Comment by Lawin0129** [comment]
> I mean era got 4.5 working on their backend a while ago so it’s definitely possible

Yes because of their ssl bypass dll, not to do with the backend

**Comment by wiks1skid** [comment]
i have found a way, but its really dumb but it works, download the login fix rift paks, make a cobalt redirect on port 8010 and set your backend on port 8010 and it should work, if you dont want to change your backend port i will makke a repo with everything and a scuffed fix (it redirects every request from port 8010 to 3551(with a js script)
![image_2024-04-08_194815370](https://github.com/Lawin0129/LawinServerV2/assets/150806927/1c523fe7-9bd4-44da-ba57-260820014299)

**Comment by 5XGhost143** [comment]
use Starfall Cobalt is buggy on 4.x

**Comment by wiktorwiktor11** [comment]
i used to be a dumbass back in the day. ignore ts

**Comment by 5XGhost143** [comment]
you literally coded a ssl bypass in pak you didnt even fix cobalt right?

**Comment by wiktorwiktor11** [comment]
rift used to have paks for the fix, which was really just a hotfix so i legit opened it up with a hex editor and edited the port in the pak manually...
