### ISSUE TITLE
How to use without discord?

### ISSUE THREAD

**Issue by Ucda1212** [Lawin0129/LawinServerV2#112]
I try to keep away for personal reasons, is there any way to get it without Discord?

**Comment by xLoigi** [comment]
You would need to make a way to interact with it (creating accounts, getting details, ...) but if you have that you can just comment out line 59 in index.js and the bot will no longer be used.

**Comment by Ucda1212** [comment]
Thanks! If that's all I need to make it work, I'll mark this as closed.

**Comment by xLoigi** [comment]
No problem, that should be all you need to do.

**Comment by Ucda1212** [comment]
Thanks, it works
