### ISSUE TITLE
its giving me an error about a token thing

### ISSUE THREAD

**Issue by Lolhchvuv** [Lawin0129/LawinServerV2#120]
![image](https://github.com/Lawin0129/LawinServerV2/assets/95657075/3a669747-61ac-4a7e-9a2e-cb23b6b21094)
it keeps saying this im using the newest verison of lawinv2

**Comment by xLoigi** [comment]
You need to add an discord token

**Comment by Lolhchvuv** [comment]
oh ok

**Comment by Lolhchvuv** [comment]
ok thanks
