### ISSUE TITLE
How to add things do the item shop?

### ISSUE THREAD

**Issue by Lolhchvuv** [Lawin0129/LawinServerV2#121]
I only know 2 things for the item shop AthenaCharacter: and AthenaGlider: what other ones are there so i can add more things

**Comment by notnotghosty** [comment]
Emotes are AthenaDance, Wraps are AthenaItemWrap, and Pickaxes are AthenaPickaxe. I'll tell you how to add others when I find out how to add them.

**Comment by Lolhchvuv** [comment]
ok

**Comment by Lolhchvuv** [comment]
i found the thing i wanted
