### ISSUE TITLE
Unable to login to fortnite servers. Please try again later.

### ISSUE THREAD

**Issue by electricsteve** [Lawin0129/LawinServerV2#124]
So I get this error when starting fortnite:
![image](https://github.com/Lawin0129/LawinServerV2/assets/96793824/269d220b-3283-4984-be9e-e4712b766aff)
Do I need to use a custom launcher or smt?

**Comment by Tiger15cub** [comment]
Hi, this does not work on latest and probibly never will, i think chapter 3 season 3 (maybe earlier) is the last supported version.

**Comment by electricsteve** [comment]
oh ok.
