### ISSUE TITLE
V-Bucks 

### ISSUE THREAD

**Issue by LoigiTV** [Lawin0129/LawinServerV2#16]
Can you change the amount of vbucks that each Account has and the Days remaning on the battle pass?

**Comment by cedriclmao** [comment]
It should be in Config/DefaultProfiles/common_core.json!

Look for "Currency:MtxPurchased" and than change the quantity to the vbucks you want.

After that restart your server. The new V-Bucks count will only be shown to accounts which are created after the change.

**Comment by LoigiTV** [comment]
Is there a way to manage each account different with vbucks?

**Comment by cedriclmao** [comment]
> Author

yeah you have to do it with a database then
