### ISSUE TITLE
MatchMaker

### ISSUE THREAD

**Issue by LoigiTV** [Lawin0129/LawinServerV2#18]
![Screenshot 2022-12-19 201618](https://user-images.githubusercontent.com/79259439/208502697-c1e05f99-9ae0-4fba-9662-9c61ff3e0dd1.png)

Does this works with the open source matchmaker and can you duplicate it for other game modes?

**Comment by zinx-YT** [comment]
i mean test your self

**Comment by Lawin0129** [comment]
Check out the new stuff in config.json

**Comment by LoigiTV** [comment]
Can you have a Server for each mode? Is it possible to delete specific mode or add more?
