### ISSUE TITLE
LawinServerV2 problems

### ISSUE THREAD

**Issue by Repressoh** [Lawin0129/LawinServerV2#2]
So, after setting up the server and logging in, I wanted to try some of the new features like the friend requests and parties.

I used 2 clients on 7.30 (with `FortniteLauncher.exe -NOSSLPINNING -skippatchcheck -epicportal -HTTP=WinINet` as args ) connected to a LawinServerV2 with Figlet to redirects Fortnite servers, [this is the script I use](https://pastebin.com/ZuPyf3uV) .

Then after successfully logging in on both clients, i sent the friend requests to each other, but the friend request appear only after logging out and relogging in, same thing for accepting it.

After accepting the friend requests, I logged out and relogged in but both profiles appear offline from the friend list.

So, in resume, seems like the client doesn't receive (or send) updates from LawinServerV2.

### HOW TO RESOLVE = https://github.com/Lawin0129/LawinServerV2/issues/2#issuecomment-1279784814

**Comment by AntogamerYT** [comment]
I helped him and I would like to know if there's a way to not use port 80 for xmpp, since I already have a webserver on that port because i host lawinserver on a vps

**Comment by AntogamerYT** [comment]
@Lawin0129 sorry to bother you, but do you have any idea of what's causing this? (friend requests and party that don't work, season X and higher that [gets stuck on the queue checking](https://user-images.githubusercontent.com/64664639/195995739-98687165-f875-4c01-a288-5aab8bc4d8f9.png))

**Comment by Lawin0129** [comment]
Are both of your 7.30 clients connected to xmpp?

**Comment by Lawin0129** [comment]
> I helped him and I would like to know if there's a way to not use port 80 for xmpp, since I already have a webserver on that port because i host lawinserver on a vps EDIT: Season X and higher also block on the queue check

Sadly on localhost there isn't really another way because even if you change the xmpp port from "CloudStorage/DefaultEngine.ini" fortnite will still use port 80

**Comment by Lawin0129** [comment]
And also what launcher are you using for season x

**Comment by AntogamerYT** [comment]
@Lawin0129 I'm using a launch.bat with this args:
```
FortniteClient-Win64-Shipping_EAC.exe -NOSSLPINNING -skippatchcheck -epicportal -HTTP=WinINet
```
(I have to start with EAC because if i don't fortnite crashes)

**Comment by Lawin0129** [comment]
Yeah that's why it's not working, you can use this launcher https://github.com/NeoniteDev/NeoniteV2/raw/aac5e039a98dea00b4d0bf46ddc4a17d05e44076/public/launcher.zip
but don't expect builds 9.40-10.40 to have xmpp because cloudstorage is disabled on those builds

**Comment by Lawin0129** [comment]
@Repressoh The reason that you're having issues with friend requests and friends not being online is because your clients aren't connected to xmpp

**Comment by AntogamerYT** [comment]
> @Repressoh The reason that you're having issues with friend requests and friends not being online is because your clients aren't connected to xmpp

That's strange, how does the client connect to xmpp then? Do i have to only redirect .ol.epicgames.? because I'm currently redirecting .epicgames. on fiddler

**Comment by AntogamerYT** [comment]
> Yeah that's why it's not working, you can use this launcher https://github.com/NeoniteDev/NeoniteV2/raw/aac5e039a98dea00b4d0bf46ddc4a17d05e44076/public/launcher.zip but don't expect builds 9.40-10.40 to have xmpp because cloudstorage is disabled on those builds

![image](https://user-images.githubusercontent.com/64664639/195998794-fdbb847f-da3e-48aa-9826-e765e69dba39.png)
uhhhhhhhhhh

**Comment by Lawin0129** [comment]
Show me your fiddlerscript

**Comment by Lawin0129** [comment]
> > @Repressoh The reason that you're having issues with friend requests and friends not being online is because your clients aren't connected to xmpp
> 
> That's strange, how does the client connect to xmpp then? Do i have to only redirect .ol.epicgames.? because I'm currently redirecting .epicgames. on fiddler

Check "CloudStorage/DefaultEngine.ini", I use cloudstorage to redirect it

**Comment by AntogamerYT** [comment]
Yep, that was the issue, i figured it out a minute before you answered lol, tysm

**Comment by Lawin0129** [comment]
No problem :)

**Comment by Repressoh** [comment]
Another question, on my local pc its stuck on the queue, but on my second pc isn't. I tried to redownload the build but i have the same problem. I saw on the console that looks like that a ssl request fails. Any idea of what I can do?

![image](https://user-images.githubusercontent.com/85702320/196000286-50be211e-6c35-4640-bef2-7f4d5daabf98.png)


### The logs for the error:

LogOnlineAccount: Display: [UOnlineAccountCommon::ContinueLoggingIn] Login: Checking Epic services queue... (LoginWaitingRoom)

LogHttp: Warning: 00007FE58D23FB40: request failed, libcurl error: 35 (SSL connect error)

LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 0 (  Trying 3.211.219.60...)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 1 (TCP_NODELAY set)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 2 (Connected to fortnitewaitingroom-public-service-prod.ol.epicgames.com (3.211.219.60) port 443 (#3))
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 3 (ALPN, offering http/1.1)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 4 (Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 5 (TLSv1.2 (OUT), TLS header, Certificate Status (22):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 6 (TLSv1.2 (OUT), TLS handshake, Client hello (1):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 7 (TLSv1.2 (IN), TLS handshake, Server hello (2):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 8 (TLSv1.2 (IN), TLS handshake, Certificate (11):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 9 (TLSv1.2 (IN), TLS handshake, Server key exchange (12):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 10 (TLSv1.2 (IN), TLS handshake, Server finished (14):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 11 (TLSv1.2 (OUT), TLS handshake, Client key exchange (16):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 12 (TLSv1.2 (OUT), TLS change cipher, Client hello (1):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 13 (TLSv1.2 (OUT), TLS handshake, Finished (20):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 14 (TLSv1.2 (IN), TLS alert, Server hello (2):)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 15 (error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac)
LogHttp: Warning: 00007FE58D23FB40: libcurl info message cache 16 (Closing connection 3)

**Comment by AntogamerYT** [comment]
> Show me your fiddlerscript

@Lawin0129 I fixed the update problem, but the launcher you gave me redirects all the requests to localhost:5595

This is the fiddlerscript btw

```
import Fiddler;

class Handlers
{
    static function OnBeforeRequest(oSession: Session) {
        if (oSession.hostname.Contains(".epicgames."))
        {
            if (oSession.HTTPMethodIs("CONNECT"))
            {
                oSession["x-replywithtunnel"] = "FortniteTunnel";
                return;
            }

            oSession.fullUrl = "http://redacted_ip:8080" + oSession.PathAndQuery;
        }
    }
}
```

**Comment by Lawin0129** [comment]
> > Show me your fiddlerscript
> 
> @Lawin0129 I fixed the update problem, but the launcher you gave me redirects all the requests to localhost:5595
> 
> This is the fiddlerscript btw
> 
> ```
> import Fiddler;
> 
> class Handlers
> {
>     static function OnBeforeRequest(oSession: Session) {
>         if (oSession.hostname.Contains(".epicgames."))
>         {
>             if (oSession.HTTPMethodIs("CONNECT"))
>             {
>                 oSession["x-replywithtunnel"] = "FortniteTunnel";
>                 return;
>             }
> 
>             oSession.fullUrl = "http://redacted_ip:8080" + oSession.PathAndQuery;
>         }
>     }
> }
> ```

Change the backend port to 5595

**Comment by AntogamerYT** [comment]
oh and forgot to say, the launcher doesn't open again after i close it

**Comment by PRO100KatYT** [comment]
Close fiddler, open the launcher and then open fiddler again.

**Comment by AntogamerYT** [comment]
@PRO100KatYT thank you

**Comment by AntogamerYT** [comment]
@Lawin0129 i host the backend on a vps (and that's why i censored the ip), should i just redirect all the localhost:5595 requests to the vps ip?

**Comment by Lawin0129** [comment]
yes

**Comment by AntogamerYT** [comment]
> yes

doesn't work

![image](https://user-images.githubusercontent.com/64664639/196002380-48bee366-0414-4303-b633-cf5dd5d3f23e.png)


![image](https://user-images.githubusercontent.com/64664639/196002385-9ef9cbd2-f043-43c9-8a82-29d21989dcac.png)

**Comment by Lawin0129** [comment]
hostname only contains "localhost"

**Comment by Lawin0129** [comment]
change `oSession.hostname == "localhost:5595"` to `oSession.fullUrl.Contains("localhost:5595")`

**Comment by AntogamerYT** [comment]
@Lawin0129 thank you, you're the best!

**Comment by AntogamerYT** [comment]
> Yeah that's why it's not working, you can use this launcher https://github.com/NeoniteDev/NeoniteV2/raw/aac5e039a98dea00b4d0bf46ddc4a17d05e44076/public/launcher.zip but don't expect builds 9.40-10.40 to have xmpp because cloudstorage is disabled on those builds

Why is cloudstorage disabled btw?

**Comment by Lawin0129** [comment]
It's to bypass an error which closes your game

**Comment by Lawin0129** [comment]
@Repressoh What launcher are you using?

**Comment by Repressoh** [comment]
> @Repressoh What launcher are you using?

this https://drive.google.com/file/d/1xXkIY4YfF1_pSRYdy5BtFC4yQCOzutmU/view

**Comment by Lawin0129** [comment]
What does it show in fiddler?

**Comment by Repressoh** [comment]
> What does it show in fiddler?

Sorry for the long time, for me was night

![image](https://user-images.githubusercontent.com/85702320/196022089-e4a187b7-f8f3-466b-b732-6f2a739bb988.png)

**Comment by Lawin0129** [comment]
@Repressoh Can I see your fiddler script?

**Comment by Repressoh** [comment]
> @Repressoh Can I see your fiddler script?

https://pastebin.com/ZuPyf3uV

**Comment by AntogamerYT** [comment]
@Lawin0129 forgot to say (I also asked this in lawinserver v1), how do I put cosmetics in the item shop?

**Comment by Lawin0129** [comment]
You can't do it in Lawin V2

**Comment by AntogamerYT** [comment]
> You can't do it in Lawin V2

Then what's the use of [this file](https://github.com/Lawin0129/LawinServerV2/blob/main/routes/storefront.js)?

**Comment by Nightmaresuwu** [comment]
> You can't do it in Lawin V2

is it working with atlas mongo db?

**Comment by AntogamerYT** [comment]
> > You can't do it in Lawin V2
> 
> is it working with atlas mongo db?

I guess so, you just need a mongodb database, it should work

**Comment by Nightmaresuwu** [comment]
> > > You can't do it in Lawin V2
> > 
> > 
> > is it working with atlas mongo db?
> 
> I guess so, you just need a mongodb database, it should work

yeah but idk i cant log in

**Comment by Repressoh** [comment]
> > > > You can't do it in Lawin V2
> > > 
> > > 
> > > is it working with atlas mongo db?
> > 
> > 
> > I guess so, you just need a mongodb database, it should work
> 
> yeah but idk i cant log in

just go on the dashboard, click connect, connect your application, nodejs on top and copy the link that gives and change password to the user password you created in mongo. then paste it in the configuration and you're done

**Comment by Lawin0129** [comment]
> > You can't do it in Lawin V2
> 
> Then what's the use of [this file](https://github.com/Lawin0129/LawinServerV2/blob/main/routes/storefront.js)?

It's there because I could add it in the future

**Comment by Lawin0129** [comment]
@Repressoh did you fix it?

**Comment by Repressoh** [comment]
> @Repressoh did you fix it?

nop

**Comment by Lawin0129** [comment]
I saw your other closed issue, is that the same issue or not?

**Comment by Repressoh** [comment]
> I saw your other closed issue, is that the same issue or not?

i think it is, but its not a build problem because i redownloaded it and i have the same issue

**Comment by Nightmaresuwu** [comment]
I have the same problem

> > I saw your other closed issue, is that the same issue or not?
> 
> i think it is, but its not a build problem because i redownloaded it and i have the same issue

![Uploading image.png…]()

**Comment by Nightmaresuwu** [comment]
> > I saw your other closed issue, is that the same issue or not?
> 
> i think it is, but its not a build problem because i redownloaded it and i have the same issue

i have the same problem
![Screenshot 2022-10-16 170644](https://user-images.githubusercontent.com/97969068/196042979-d4f8dd89-55bf-481f-ae56-1e21ada45868.png)

**Comment by Repressoh** [comment]
i think its more appropriate to move to issue #1 at this point

**Comment by Lawin0129** [comment]
It's clearly a launcher issue, I can't really do anything sadly

**Comment by Lawin0129** [comment]
> i think its more appropriate to move to issue #1 at this point

yeah I'll close this down as completed

**Comment by Nightmaresuwu** [comment]
> It's clearly a launcher issue, I can't really do anything sadly

i dont use a launcher i using the launcher.bat

**Comment by AntogamerYT** [comment]
> > > You can't do it in Lawin V2
> > 
> > 
> > Then what's the use of [this file](https://github.com/Lawin0129/LawinServerV2/blob/main/routes/storefront.js)?
> 
> It's there because I could add it in the future

oh kk

**Comment by Lawin0129** [comment]
> > It's clearly a launcher issue, I can't really do anything sadly
> 
> i dont use a launcher i using the launcher.bat

that's why

**Comment by Lawin0129** [comment]
Everyone with logging in issues go to #1
I'm closing this issue down as completed

**Comment by AntogamerYT** [comment]
> > > It's clearly a launcher issue, I can't really do anything sadly
> > 
> > 
> > i dont use a launcher i using the launcher.bat
> 
> that's why

I also use the launcher.bat on season 7 with the custom fortnitelauncher and it works fine,

**Comment by Nightmaresuwu** [comment]
then what should i use?

**Comment by Lawin0129** [comment]
> > > > It's clearly a launcher issue, I can't really do anything sadly
> > > 
> > > 
> > > i dont use a launcher i using the launcher.bat
> > 
> > 
> > that's why
> 
> I also use the launcher.bat on season 7 with the custom fortnitelauncher and it works fine,

if you use custom fortnitelauncher that'll work
