### ISSUE TITLE
Webserver in Port 80

### ISSUE THREAD

**Issue by AToska21** [Lawin0129/LawinServerV2#20]
Hi! I already have a Webserver on port 80 but the lawinserver needs it for xmpp. How do I get around this?

**Comment by Lawin0129** [comment]
No way around this sorry

**Comment by AToska21** [comment]
> No way around this sorry

damn ok what about hosting our own matchmaker and xmpp on lawinserverV1

**Comment by Lawin0129** [comment]
@AToska21 Matchmaker has now been implemented into Lawin V2
