### ISSUE TITLE
1/10 times an endpoint will 404.

### ISSUE THREAD

**Issue by Ender-0001** [Lawin0129/LawinServerV2#24]
on every build i have tested 4.2 10.40 6.10 12.41 etc a random endpoint has 404'ed changes everytime, happens at any time with the error "Token is missing key ID value"

**Comment by Lawin0129** [comment]
Can I have some screenshots or something

**Comment by Ender-0001** [comment]
I'll see if I can get some pictures of the Fortnite log and fiddler

**Comment by Lawin0129** [comment]
Launcher issue
