### ISSUE TITLE
Host Lawin on a VPS without Fiddler

### ISSUE THREAD

**Issue by zAlwaysTheSun** [Lawin0129/LawinServerV2#29]
Hello, 
I already looked at issue #2 , but I didn't really understand how to host LawinServer for our friends without using Fiddler, should we make a Python script? Does a launcher already allow you to do this?
Thank you for your reply.

**Comment by Lawin0129** [comment]
You can use this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/1021195280739225694/1063931735852724294/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml to whatever your public VPS IP is.
