### ISSUE TITLE
could you please make a working matchmaker

### ISSUE THREAD

**Issue by Jyzodev** [Lawin0129/LawinServerV2#3]

**Comment by Lawin0129** [comment]
It's supposed to work but my heroku matchmaker is down

**Comment by Jyzodev** [comment]
> It's supposed to work but my heroku matchmaker is down

Okay but i have problems launching with Fiddler i use the script that everyone uses

**Comment by Jyzodev** [comment]
i want to redirect epicgames server to the ip of the machine i host on

**Comment by AntogamerYT** [comment]
> It's supposed to work but my heroku matchmaker is down

Heroku is going to remove free dynos soon, you should move it to something else/ make it open source so people can host it

**Comment by AntogamerYT** [comment]
> i want to redirect epicgames server to the ip of the machine i host on

try this script

```
import Fiddler;

class Handlers
{
    static function OnBeforeRequest(oSession: Session) {
        if (oSession.hostname.Contains(".epicgames.") || oSession.fullUrl.Contains("localhost:5595"))
        {
            if (oSession.HTTPMethodIs("CONNECT"))
            {
                oSession["x-replywithtunnel"] = "FortniteTunnel";
                return;
            }

            oSession.fullUrl = "http://localhost:8080" + oSession.PathAndQuery;
        }
    }
}
```

**Comment by PRO100KatYT** [comment]
> Heroku is going to remove free dynos soon, you should move it to something else/ make it open source so people can host it

[It is open source](https://github.com/Lawin0129/FortMatchmaker)

**Comment by Jyzodev** [comment]
> > i want to redirect epicgames server to the ip of the machine i host on
> 
> try this script
> 
> ```
> import Fiddler;
> 
> class Handlers
> {
>     static function OnBeforeRequest(oSession: Session) {
>         if (oSession.hostname.Contains(".epicgames.") || oSession.fullUrl.Contains("localhost:5595"))
>         {
>             if (oSession.HTTPMethodIs("CONNECT"))
>             {
>                 oSession["x-replywithtunnel"] = "FortniteTunnel";
>                 return;
>             }
> 
>             oSession.fullUrl = "http://localhost:8080" + oSession.PathAndQuery;
>         }
>     }
> }
> ```

Do i need all my friends to install lawinv2 or just fiddler and put the ip of my machine?

**Comment by AntogamerYT** [comment]
> > Heroku is going to remove free dynos soon, you should move it to something else/ make it open source so people can host it
> 
> [It is open source](https://github.com/Lawin0129/FortMatchmaker)

oh, didn't notice

**Comment by AntogamerYT** [comment]
@Jyzodev if you host a lawinserver you just need your friends to put the ip of your machine (if you host it on your pc make sure to forward port 8080 and 80)

**Comment by Jyzodev** [comment]
> @Jyzodev if you host a lawinserver you just need your friends to put the ip of your machine (if you host it on your pc make sure to forward port 8080 and 80)

Okayy ty...

**Comment by LoigiTV** [comment]
> > Heroku is going to remove free dynos soon, you should move it to something else/ make it open source so people can host it
> 
> [It is open source](https://github.com/Lawin0129/FortMatchmaker)

Do you know how to set it up?
