### ISSUE TITLE
Fiddler

### ISSUE THREAD

**Issue by Dragonterror** [Lawin0129/LawinServerV2#33]
What fiddlerscript should I use? Any launcher too? I'm new to this stuff.

**Comment by Kyro999** [comment]
reup please, I really need a launcher

**Comment by LoigiTV** [comment]
Use this https://github.com/Jurij15/FortniteLauncher

**Comment by Lawin0129** [comment]
You can use this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/1021195280739225694/1063931735852724294/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml to whatever your public VPS IP is.
