### ISSUE TITLE
S4 login errors

### ISSUE THREAD

**Issue by Noggo123** [Lawin0129/LawinServerV2#41]
its impossible to get into the lobby

**Comment by Lawin0129** [comment]
Not a backend issue,
try this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml if you are also hosting for your friends.
