### ISSUE TITLE
Launcher?

### ISSUE THREAD

**Issue by Kyro999** [Lawin0129/LawinServerV2#43]
How do I launch into the actual game? there are no launchers Lawin Server V2. I tried making my own using old SSL Injection DLL but it just doesn't work so idek anymore. Please help

**Comment by LoigiTV** [comment]
Use this https://github.com/Jurij15/FortniteLauncher

**Comment by Kyro999** [comment]
It doesn't work, when I try launching current fornite with that launcher it gives me errors, it doesn't let me in. i need a launcher for the current FN Build

**Comment by Kyro999** [comment]
It doesn't work, when I try launching current fornite with that launcher it gives me errors, it doesn't let me in. i need a launcher for the current FN Build

**Comment by LoigiTV** [comment]
The current build is not supported by LawinServer

**Comment by Lawin0129** [comment]
You can use this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml if you are also hosting for your friends.

**Comment by Kyro999** [comment]
Hey, so i tried the launcher and everytime i launch it just crashes and says "fatal error"
