### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by LoigiTV** [Lawin0129/LawinServerV2#44]
I noticed that LawinServerV2 dosent support Linux (or just Ubuntu) and i think i'd would be very nice if you could add Linux support

**Comment by 2vb** [comment]
You can run it by typing the commands into the terminal instead of using the included .bat files.
Make sure you have Node installed on your machine.
To install packages run `npm i` and wait for it to finish.
To start LawinServerV2, run `node index.js` (Might have to `sudo node index.js`)

**Comment by Lawin0129** [comment]
I thought it'd just work by default?

**Comment by Lawin0129** [comment]
My friend hosted Lawin V2 on Ubuntu and it worked perfectly fine

**Comment by 2vb** [comment]
> I thought it'd just work by default?
> My friend hosted Lawin V2 on Ubuntu and it worked perfectly fine

worked fine by default for me as well

**Comment by LoigiTV** [comment]
ok, wierd.

**Comment by 2vb** [comment]
> ok, wierd.

Can you provide more information on the error?

**Comment by Lawin0129** [comment]
Is your Node.js up to date on your Linux machine?

**Comment by LoigiTV** [comment]
**It just magically fixed itself.** 

But thank for trying to help!
