### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Scarcro20** [Lawin0129/LawinServerV2#45]
help me plz how join the lawinserverv2
just how

**Comment by LoigiTV** [comment]
If you already set it up you need to download Fiddler. When you downloaded Fiddler you need to click on "Tools" and then on "Options". If you done that click on "HTTPS". Then check that "Capture HTTPS CONNECTs", "Decrypt HTTPS traffic" and "Ignore server certificate errors" are checked. Then click on "Actions" and on "Trust root certificate". When it gives you a waring that looks like this ![Screenshot 2023-05-14 230523](https://github.com/Lawin0129/LawinServerV2/assets/79259439/3c176547-e1c7-44d7-99ef-27459919cd64) click yes and in the following windows click also yes. If you done that close all the options windows and click on "FiddlerScript" remove everything thats already in there and paste this [script.txt](https://github.com/Lawin0129/LawinServerV2/files/11472941/script.txt) in it. Click on "Save Script" and minimize Fiddler. Start your LawinServerV2 and then start Fortnite.

If you have any further questions DM me on Discord Loigi#1714

**Comment by Lawin0129** [comment]
You can use this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml if you are also hosting for your friends.
