### ISSUE TITLE
Launchers

### ISSUE THREAD

**Issue by xLoigi** [Lawin0129/LawinServerV2#49]
I saw the launchers channel in your discord and i wanted to ask if you could also upload the starting for 10.40 and 12.41 or just more builds in general

**Comment by LoigiTV** [comment]
Sorry i meant 11.50

**Comment by Lawin0129** [comment]
You can use this launcher: [EraLauncher_for_LawinV2.rar](https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar)
just edit the Backend IP in Settings/FortMPConfig.toml if you are also hosting for your friends.
