### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by W0lfyN4ti** [Lawin0129/LawinServerV2#51]
hey I just wanted to ask if you can add support for macOS?
Kind regards, Natalie

**Comment by LoigiTV** [comment]
It should have it out of the box i think
-Do you have Nodejs installed?
-Does it do anything if you open it?
-Does it give you an error (if yes, please Screenshot and send)

**Comment by W0lfyN4ti** [comment]
well the backend runs, but I need a launcher for the game and a way to redirect it. all the launchers/ssl bypass files are windows only

**Comment by xLoigi** [comment]
You could host Fiddler on a Windows Maschine and add to Fortnite the argument -httpproxy=[the Windows IP adress]

**Comment by Lawin0129** [comment]
Not a lawinserver issue
