### ISSUE TITLE
Matchmaker error

### ISSUE THREAD

**Issue by xLoigi** [Lawin0129/LawinServerV2#59]
![image](https://github.com/Lawin0129/LawinServerV2/assets/79259439/558241d2-2556-497e-9f04-d54f3e8dc4e6)
The matchmaker does not work on 8.51

**Comment by AntogamerYT** [comment]
Works for me

**Comment by xLoigi** [comment]
On witch build?

**Comment by AntogamerYT** [comment]
8.51, 7.40

**Comment by xLoigi** [comment]
Did you use the newest backend version?

**Comment by AntogamerYT** [comment]
Not from the commit of 2 days ago because it's all stuff related to the latest fortnite version, but i have the commit before this one, yea

**Comment by xLoigi** [comment]
Ok. I have the same version. Very Wierd

**Comment by xLoigi** [comment]
Magicly fixed itself

**Comment by xLoigi** [comment]
Just started again happening on a vps
