### ISSUE TITLE
I managed to get it working but I can't join my other accounts party.

### ISSUE THREAD

**Issue by joshuavalenci** [Lawin0129/LawinServerV2#6]
Idk if I did it wrong but my other account is not showing online even tho it is. Please help, and thanks for giving the community this amazing server.
![image](https://user-images.githubusercontent.com/29871540/196667060-510d93b7-2729-4c99-9965-f308983f27d8.png)

**Comment by Jyzodev** [comment]
You dont have any xmpp hosted

**Comment by Jyzodev** [comment]
Dm me on discord : jyzo.#6858 
So i can help you setup lawinserverV2 xmpp

**Comment by joshuavalenci** [comment]
alright I added you

**Comment by AntogamerYT** [comment]
you need to redirect your xmpp server using CloudStorage/DefaultEngine.ini, just change the address
