### ISSUE TITLE
How can i mask my IP while also not using Radmin?

### ISSUE THREAD

**Issue by dontknowsmthehere** [Lawin0129/LawinServerV2#71]
I've been trying many different ways:

I've tried Radmin and while it works i dont want players to specifically download Radmin to do this.

I've tried PLAYIT.GG but in the Reboot launcher it says "The address [..] doesnt work." or something similiar.

Also, if possible, how could i create a launcher that doesn't require you to put all the info to login onto the server (so like you launch the game and thats it) if possible?

Thank you.

**Comment by xLoigi** [comment]
Where did you put you Play it.gg address? 

So you mean that you login in onetime into the launcher and automaticly get logged in in to fortnite without putting the Login Detail in sepratly in it?

**Comment by dontknowsmthehere** [comment]
> Where did you put you Play it.gg address?
> 
> So you mean that you login in onetime into the launcher and automaticly get logged in in to fortnite without putting the Login Detail in sepratly in it?

No when I go on Backend info and ping the server (play it.gf, both IP address and domain) and click on Start Backend its going to say "The Ip (ip):8080 doesnt work."

**Comment by xLoigi** [comment]
Yea LawinV2 does not work with reboot. You need to manual inject the reboot.dll into the game

**Comment by dontknowsmthehere** [comment]
> Yea LawinV2 does not work with reboot. You need to manual inject the reboot.dll into the game

So players that try to connect get the same error, I did get it running but what's up with that (I can connect to the Radmin IP but they can't)

**Comment by xLoigi** [comment]
I know. Reboot Launcher in general is not compatible with LawinV2. You could use the modified Era Launcher.

**Comment by dontknowsmthehere** [comment]
> I know. Reboot Launcher in general is not compatible with LawinV2. You could use the modified Era Launcher.

Where can I find it?

**Comment by xLoigi** [comment]
https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar Here, it was in another issue. You need to modify the FortMPConfig.toml

**Comment by dontknowsmthehere** [comment]
> https://cdn.discordapp.com/attachments/927739901540188200/1112073800364867594/EraLauncher_for_LawinV2.rar Here, it was in another issue. You need to modify the FortMPConfig.toml

It seems to give players an infinite: "Checking epic games queue.."
Any fix?

**Comment by xLoigi** [comment]
Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?

**Comment by dontknowsmthehere** [comment]
> Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?

Backend is online, showing that XMPP is 80, 8080 etc, The ip and port is right, the build is 12.41

**Comment by dontknowsmthehere** [comment]
> Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?

So it might work but i havent tested, i think i've done a mistake but i had a question, where can i find a good, possibly free, VPS to run this backend?

**Comment by dontknowsmthehere** [comment]
> Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?

I am sure the IP is right and it still gives Unable to check Fortnite queue. whats up with that? both 8.40 and 12.41

**Comment by xLoigi** [comment]
> > Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?
> 
> So it might work but i havent tested, i think i've done a mistake but i had a question, where can i find a good, possibly free, VPS to run this backend?

I believe that there is only very cheap hosters but no free

**Comment by xLoigi** [comment]
> > Is your backend online? Is the ip and port right in FortMPConfig.toml? Which Build are you using?
> 
> I am sure the IP is right and it still gives Unable to check Fortnite queue. whats up with that? both 8.40 and 12.41

Can you provide screenshots?
