### ISSUE TITLE
Login to Lawin V2 without using in game login

### ISSUE THREAD

**Issue by staydevoooo** [Lawin0129/LawinServerV2#8]
I’m creating a custom Fortnite launcher and was wondering if it’s possible to login to a LawinV2 account straight from the launcher to avoid logging in when the game opens (via launch arguments or something)

**Comment by PRO100KatYT** [comment]
You can use these launch arguments: -AUTH_LOGIN=email -AUTH_PASSWORD=password -AUTH_TYPE=epic

The auth_type has to be epic.

**Comment by staydevoooo** [comment]
> You can use these launch arguments: -AUTH_LOGIN=email -AUTH_PASSWORD=password -AUTH_TYPE=epic
> 
> The auth_type has to be epic.

This works! Thank you!

**Comment by fmgnio1221** [comment]
talking about custom launcher, what in game dll i should use to get in game

**Comment by xLoigi** [comment]
What do you mean by ingame?
