### ISSUE TITLE
Please add settings saving

### ISSUE THREAD

**Issue by secret-pommes** [Lawin0129/LawinServerV2#9]
Please add settings saving

please lawin :)

**Comment by staydevoooo** [comment]
yes pls

**Comment by staydevoooo** [comment]
IMO it’s better like that when it saves the same for all seasons, for people who play multiple versions frequently

**Comment by secret-pommes** [comment]
> If I do add it, I won't make it save separately for each build because that can be abused.

can you do it so that it saves like in lawinserver v1 as a file ClientSettings.Sav
in the server folder

**Comment by Lawin0129** [comment]
Done
