### ISSUE TITLE
…

### ISSUE THREAD

**Issue by notshrimps** [Lawin0129/LawinServerV2#91]
I start the game path with the old launcher and backend connect but I can’t login

**Comment by xLoigi** [comment]
What launcher?

**Comment by notshrimps** [comment]
From lawin for season 4

**Comment by xLoigi** [comment]
The Era launcher?

**Comment by notshrimps** [comment]
https://drive.google.com/file/d/1hdqBupLjqFAvRBM5-bdaCGpShaFZpHgv/view?usp=sharing This one

**Comment by xLoigi** [comment]
Ohhhhhhh, what kind of redirect do you use?

**Comment by notshrimps** [comment]
From lawin v1 backend

xLoigi ***@***.***> schrieb am Di. 21. Nov. 2023 um 12:50:

**Comment by notshrimps** [comment]
From lawin v1 backend

**Comment by xLoigi** [comment]
You cant you that. You need to use a SLL Bypass or Fiddler Classic.

**Comment by xLoigi** [comment]
Or you can add a start argument to the redirect

**Comment by notshrimps** [comment]
How to do that

**Comment by xLoigi** [comment]
Can you go to Discord?

**Comment by notshrimps** [comment]
yes

**Comment by xLoigi** [comment]
My name is Loigi on discord
